### ISSUE TITLE
Frontend Team - Lisiting Page Blob

### ISSUE THREAD

**Issue by adityamahajan-io** [devscollab/skill-board#13]
The Blob on the listing page is overlapping the contents of the page. The blob is expected to be behind the page contents. Find a way to fix that.
![Annotation 2020-08-25 095614](https://user-images.githubusercontent.com/66865722/91122950-3d4cc100-e6b9-11ea-92d9-92b795d8a9ba.png)

**Comment by bagdechirag** [comment]
On it

**Comment by adityamahajan-io** [comment]
Looks Good!
