### ISSUE TITLE
Frontend Team - Lisiting Page Top-Bar

### ISSUE THREAD

**Issue by adityamahajan-io** [devscollab/skill-board#14]
Add a top bar to the listing page. As shown in the design
![Annotation 2020-08-25 095807](https://user-images.githubusercontent.com/66865722/91123049-7dac3f00-e6b9-11ea-971d-af2f99ed65bc.png)

**Comment by Atharv-Deshmukh** [comment]
On it!

**Comment by tejasmorkar** [comment]
# Problems 

**The Logo is not available on the navbar. It gives a 404 error and the alignment of the items is not according to the wireframe** 

![image](https://user-images.githubusercontent.com/35477326/91150321-dee40a80-e6d9-11ea-9087-1d569a2a92b6.png)

## The colors are not used as required. Find the colors from the Figma wireframes

# TODO

1. **href should be changed from "assets/images..." to "./assets/images..."**

2. **Elements in the navbar must be aligned properly**

3. **Color for the search icon button should be changed as per the Figma wireframe**

**Comment by MEHUL25** [comment]
On it!

**Comment by adityamahajan-io** [comment]
**Problem**
<hr>
The top-bar is not responsive. The Alignment breaks on mobile screens.
![Annotation 2020-08-25 153656](https://user-images.githubusercontent.com/66865722/91162013-22924080-e6e9-11ea-956b-51bfe9cc318f.png)

Please refer to this design while making the top bar.
![](https://user-images.githubusercontent.com/66865722/91123049-7dac3f00-e6b9-11ea-971d-af2f99ed65bc.png)

**Comment by adityamahajan-io** [comment]
On It!
