### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by tejasmorkar** [devscollab/skill-board#19]
The index.html page has a button to redirect the user to the listings page. 

### 1. Design the index.html page as per the design given below. Don't add any fields for login or signup. Just let the forward arrow button at the bottom redirect the user to the listings page.

![image](https://user-images.githubusercontent.com/35477326/91137635-48f5b300-e6cc-11ea-8197-105b77b6bdac.png)

**Comment by nupur-shiturkar** [comment]
On it.
