### ISSUE TITLE
blob background image curve shape

### ISSUE THREAD

**Issue by IzacVrushabh** [devscollab/skill-board#20]
**Describe the bug**
 blob img is not in perfect curve shape...

**Screenshots**
![img](https://user-images.githubusercontent.com/45138367/91146354-6c246080-e6d4-11ea-9c18-56e5e37f55c8.jpg)

@tejasmorkar  can i do some changes to make it better ?

**Comment by tejasmorkar** [comment]
@IzacVrushabh I'll assign someone to approve this at earliest. And then you can work on it.

**Comment by adityamahajan-io** [comment]
@IzacVrushabh Yes Sure! Go for it

**Comment by tejasmorkar** [comment]
The blob image is looking perfect with the added gradient. Nice work @IzacVrushabh

**Comment by IzacVrushabh** [comment]
> The blob image is looking perfect with the added gradient. Nice work @IzacVrushabh

thanx...

**Comment by tejasmorkar** [comment]
Hi @IzacVrushabh ,

The blob image is perfect but if it was a little bit wider then we could fit the arrow image perfectly on it for the landing page. 

So, can you increase the width so that it covers roughly a little more than 50% of the screen, say 55%?

**Comment by IzacVrushabh** [comment]
> Hi @IzacVrushabh ,
> 
> The blob image is perfect but if it was a little bit wider then we could fit the arrow image perfectly on it for the landing page.
> 
> So, can you increase the width so that it covers roughly a little more than 50% of the screen, say 55%?
> 
> ![image](https://user-images.githubusercontent.com/35477326/91212931-85f29180-e72e-11ea-97af-b28cdf192d52.png)

ok ..no problem ..im doing it
