### ISSUE TITLE
Color change for 'View Profile' & Search Icon Bg , Border Radius for Cards

### ISSUE THREAD

**Issue by Gaurav-Gaikwad-1** [devscollab/skill-board#27]
Color for View Profile' & Search Icon Bg is not according to design & cards is of rectangle shape we need to add radius to border

**Comment by tejasmorkar** [comment]
Okay. This issue is open for contribution and anyone can drop in a message if they want to work on it.

**Comment by Gaurav-Gaikwad-1** [comment]
I'm on it
