### ISSUE TITLE
Frontend Team - Profile Cards Issues.

### ISSUE THREAD

**Issue by adityamahajan-io** [devscollab/skill-board#32]
### The icons are not center aligned. The center line is marked in RED. The icons should align with the center line
![Annotation 2020-08-28 162839](https://user-images.githubusercontent.com/66865722/91553769-8e73e380-e94b-11ea-992d-08ca044b9b93.png)

### The _actual design_ for your reference. The text should be left aligned. As shown in design
![Annotation 2020-08-28 163055](https://user-images.githubusercontent.com/66865722/91553952-de52aa80-e94b-11ea-958f-5c3b7cae7146.png)

### Need more padding and spacing for mobile view. And some alignment improvements.
![Annotation 2020-08-28 163252](https://user-images.githubusercontent.com/66865722/91554128-240f7300-e94c-11ea-916a-1ba50f7e56cd.png)

**Comment by MEHUL25** [comment]
On It !!
