### ISSUE TITLE
Overlapping of Header on Cards

### ISSUE THREAD

**Issue by SuyashSonawane** [devscollab/skill-board#35]
![image](https://user-images.githubusercontent.com/35629339/91637123-af0f6c80-ea23-11ea-83b0-8902dd07d34f.png)

The header/navbar  is overlapping the cards

## Suggestion

Make the header/navbar width of 100%

**Comment by IzacVrushabh** [comment]
On it

**Comment by adityamahajan-io** [comment]
Issue Solved!
