### ISSUE TITLE
Typo in README.md and CONTRIBUTING.md files

### ISSUE THREAD

**Issue by ShamikG17** [devscollab/skill-board#57]
## There are some typos in the following lines from README.md and CONTRIBUTING.md 

![image](https://user-images.githubusercontent.com/48522231/93734271-3355a980-fbf6-11ea-956d-0a13697c5868.png)
![image](https://user-images.githubusercontent.com/48522231/93734327-7748ae80-fbf6-11ea-9e59-e966f22a6b12.png)
![image](https://user-images.githubusercontent.com/48522231/93734448-d9091880-fbf6-11ea-9602-da3fd80afbdd.png)
![image](https://user-images.githubusercontent.com/48522231/93734471-f0480600-fbf6-11ea-8317-833a6ba67a5f.png)

**I would like to work on this issue**

**Comment by tejasmorkar** [comment]
**Thanks for the catch!**

I'll assign you to this.
