### ISSUE TITLE
Adding "Preferred Pronoun" selection in registration form page under "OPTIONALS".

### ISSUE THREAD

**Issue by ShamikG17** [devscollab/skill-board#59]
## Suggestion to add a Preferred Pronoun option in the registration form.

This is to enhance the sign up page.
I would like to work on this.

**Comment by tejasmorkar** [comment]
Great suggestion @ShamikG17 
Let's wait for a review on this from the @devscollab/backend-developers so that they can add the functionality to handle the data. 

After their approval, I'll reply here and you can start working on it.

**Comment by ShamikG17** [comment]
Sure 👍🏽

**Comment by Aditya-Dawadikar** [comment]
Hello @ShamikG17, you may start contributing by adding this functionality to the user profile. Just add a new input field to the registration form. I have provided API documentation, check out this link https://skboard.herokuapp.com/
Follow the docs and modify the request body according to the need. 
This task doesn't require much attention from the backend team.
Let me know once done, I'll make the necessary changes in the first week of October.
For any doubts feel free to reach out.

for consistency, add a new field(in lowercase) named "pronoun" inside this object.
![image](https://user-images.githubusercontent.com/54301325/94445081-a9dd4300-01c4-11eb-84b4-b75aade97b69.png)

**Comment by ShamikG17** [comment]
Thanks for the instructions @Aditya-Dawadikar. I'll start working on it and make the PR  👍🏾
