### ISSUE TITLE
Make the Social icons 'clickable' on the listing page

### ISSUE THREAD

**Issue by adityamahajan-io** [devscollab/skill-board#70]
Fetch data from the SkillBoard-API and fill in the appropriate fields here. 
![1](https://user-images.githubusercontent.com/66865722/94984209-3a21dc00-0567-11eb-8da6-2cb7c602e88a.png)

**Comment by yuvraajnarula** [comment]
can you assign me this issue?

**Comment by adityamahajan-io** [comment]
@yuvraajnarula You're assigned! Go for it👍

**Comment by hambali999** [comment]
Hi! can i work on this? this is my first hacktoberfest2020

**Comment by hambali999** [comment]
Hey i cant seem to find the listing page
