### ISSUE TITLE
Add a 'Go Back' button on the 'view profile' page

### ISSUE THREAD

**Issue by adityamahajan-io** [devscollab/skill-board#71]
The button should take the user one step back in history.
![2](https://user-images.githubusercontent.com/66865722/94984357-caacec00-0568-11eb-87f5-aceea5994286.png)

**Comment by singhanurag05** [comment]
I would like to wok on this. Can you add the 'Hacktoberfest' topic to the repository because without that PRs wont be counted for Hacktoberfest

**Comment by SuvamPrasd** [comment]
Great, in terms of UX the page should have a back button so it will be great if you assign me this issue to work on @adityamahajan-io.

**Comment by adityamahajan-io** [comment]
You've been assigned. Go for it👍
