### ISSUE TITLE
Login Successful alert pop up.

### ISSUE THREAD

**Issue by sreenidhi3** [devscollab/skill-board#78]
Can I work on this issue? I feel it is a little annoying and hampers the user experience. Can i remove it and rather just log that on to the console?

**Comment by adityamahajan-io** [comment]
Haha yes! But logging it into the console wouldn't be a great idea. It'd be better to use 'sweetalert.js' 
https://sweetalert.js.org/guides/

Would you be able to to it this way?

**Comment by sreenidhi3** [comment]
Sure! I'll work on it.

**Comment by sreenidhi3** [comment]
Created Sweet Alert Pull requeste! Can you please check.
