### ISSUE TITLE
Footer containing the skillboard logo and link to github repository.

### ISSUE THREAD

**Issue by sneha-pujari** [devscollab/skill-board#94]
A footer suiting the theme of the website, which will have the logo of skillboard and the link to the skillboard Github repository.
These two items will be responsive too for viewing on various screens.

I would like to work on this issue if possible.

**Comment by tejasmorkar** [comment]
Hi @sneha-pujari, do you still want to work on it or should I mark it as open for contribution for others?

**Comment by ShamikG17** [comment]
hey @tejasmorkar is this issue still open to contribute to ?

**Comment by tejasmorkar** [comment]
Yes, it is.

**Comment by vedant-c** [comment]
Hey @tejasmorkar please check the proposed footer solution at https://vedant-c.github.io/skill-board/login.html . I have created a pull request for the same. Please let me know if there any changes required. Thank you.

**Comment by tejasmorkar** [comment]
> check the proposed footer solution at https://vedant-c.github.io/skill-board/login.html
@vedant-c 

Looks great! I've reviewed the PR and have requested some changes on the same. You can go through them and let me know if you have any queries by dropping a reply here.
